# Site settings
title: Become a Developer
email: zhivko.siderov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow my journey at Makers Academy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zsid.github.io/" # the base hostname & protocol for your site
twitter_username: zhivkosiderov
github_username:  zsid

# Build settings
markdown: kramdown